/**
 * menu-data.js
 * Dữ liệu mẫu cho thực đơn — đủ chi tiết để dùng thật (không phải data rỗng).
 * Ảnh dùng từ Unsplash (miễn phí bản quyền, unsplash.com/license).
 */

const MENU_CATEGORIES_SEED = [
  { id: 'cat_ca-phe', name: 'Cà Phê', slug: 'ca-phe', icon: '☕', description: 'Rang xay mỗi ngày tại quán' },
  { id: 'cat_tra', name: 'Trà', slug: 'tra', icon: '🍵', description: 'Trà Ô Long, trà hoa, trà trái cây' },
  { id: 'cat_da-xay', name: 'Đá Xay', slug: 'da-xay', icon: '🥤', description: 'Mát lạnh, sánh mịn' },
  { id: 'cat_banh', name: 'Bánh Ngọt', slug: 'banh-ngot', icon: '🥐', description: 'Bánh nướng thủ công mỗi sáng' },
  { id: 'cat_do-an-nhe', name: 'Đồ Ăn Nhẹ', slug: 'do-an-nhe', icon: '🥪', description: 'Bánh mặn, sandwich, salad' },
];

const MENU_ITEMS_SEED = [
  {
    id: 'menu_espresso-classico',
    name: 'Espresso Classico',
    categoryId: 'cat_ca-phe',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?q=80&w=800&auto=format&fit=crop',
    roast: 'dark',
    rating: 4.8,
    reviewCount: 214,
    description: 'Espresso nguyên chất từ hạt Arabica rang đậm, chiết xuất 25 giây, lớp crema dày mịn — dành cho người yêu vị đắng thuần khiết.',
    tags: ['best-seller', 'hot'],
    calories: 5,
    prepMinutes: 3,
    inStock: true,
  },
  {
    id: 'menu_americano',
    name: 'Americano Đá',
    categoryId: 'cat_ca-phe',
    price: 42000,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop',
    roast: 'medium',
    rating: 4.6,
    reviewCount: 178,
    description: 'Espresso pha loãng cùng nước lạnh và đá viên, giữ trọn hương thơm nguyên bản nhưng nhẹ nhàng, dễ uống cả ngày.',
    tags: ['cold'],
    calories: 10,
    prepMinutes: 3,
    inStock: true,
  },
  {
    id: 'menu_capuchino',
    name: 'Cappuccino',
    categoryId: 'cat_ca-phe',
    price: 52000,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?q=80&w=800&auto=format&fit=crop',
    roast: 'medium',
    rating: 4.9,
    reviewCount: 302,
    description: 'Tỷ lệ vàng espresso – sữa nóng – bọt sữa mịn dày 1cm, rắc thêm chút bột cacao thủ công.',
    tags: ['best-seller', 'hot'],
    calories: 120,
    prepMinutes: 5,
    inStock: true,
  },
  {
    id: 'menu_ca-phe-sua-da',
    name: 'Cà Phê Sữa Đá',
    categoryId: 'cat_ca-phe',
    price: 39000,
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0b9?q=80&w=800&auto=format&fit=crop',
    roast: 'dark',
    rating: 5.0,
    reviewCount: 456,
    description: 'Hương vị Việt Nam nguyên bản — cà phê phin rang đậm hoà cùng sữa đặc, phục vụ với đá viên to.',
    tags: ['best-seller', 'signature', 'cold'],
    calories: 180,
    prepMinutes: 6,
    inStock: true,
  },
  {
    id: 'menu_bac-xiu',
    name: 'Bạc Xỉu',
    categoryId: 'cat_ca-phe',
    price: 41000,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?q=80&w=800&auto=format&fit=crop',
    roast: 'light',
    rating: 4.7,
    reviewCount: 132,
    description: 'Nhiều sữa hơn cà phê — êm dịu, ngọt béo, phù hợp cho buổi sáng nhẹ nhàng.',
    tags: ['cold'],
    calories: 210,
    prepMinutes: 5,
    inStock: true,
  },
  {
    id: 'menu_tra-oolong',
    name: 'Trà Ô Long Đào',
    categoryId: 'cat_tra',
    price: 48000,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.7,
    reviewCount: 96,
    description: 'Trà Ô Long ủ lạnh 12 giờ, kết hợp syrup đào tự làm và thạch đào giòn sần sật.',
    tags: ['cold', 'new'],
    calories: 140,
    prepMinutes: 6,
    inStock: true,
  },
  {
    id: 'menu_tra-sen-vang',
    name: 'Trà Sen Vàng',
    categoryId: 'cat_tra',
    price: 46000,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.5,
    reviewCount: 74,
    description: 'Trà xanh Thái Nguyên ướp hương sen tự nhiên, vị thanh nhẹ, hậu ngọt kéo dài.',
    tags: ['hot', 'cold'],
    calories: 90,
    prepMinutes: 5,
    inStock: true,
  },
  {
    id: 'menu_matcha-da-xay',
    name: 'Matcha Đá Xay',
    categoryId: 'cat_da-xay',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1536013455962-e0f2a05b4a4a?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.8,
    reviewCount: 189,
    description: 'Bột matcha Uji nguyên chất xay cùng đá và sữa tươi, phủ kem whipping béo nhẹ.',
    tags: ['best-seller', 'cold'],
    calories: 260,
    prepMinutes: 7,
    inStock: true,
  },
  {
    id: 'menu_choco-da-xay',
    name: 'Chocolate Đá Xay',
    categoryId: 'cat_da-xay',
    price: 53000,
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.6,
    reviewCount: 121,
    description: 'Socola đen 70% xay mịn cùng đá, topping kem tươi và sốt chocolate rưới tay.',
    tags: ['cold'],
    calories: 310,
    prepMinutes: 7,
    inStock: true,
  },
  {
    id: 'menu_croissant-bo',
    name: 'Croissant Bơ Pháp',
    categoryId: 'cat_banh',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.9,
    reviewCount: 167,
    description: '27 lớp bơ Président cán tay, nướng giòn mỗi sáng — ăn kèm cà phê đắng là hoàn hảo.',
    tags: ['best-seller', 'new'],
    calories: 320,
    prepMinutes: 1,
    inStock: true,
  },
  {
    id: 'menu_tiramisu',
    name: 'Bánh Tiramisu',
    categoryId: 'cat_banh',
    price: 58000,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.8,
    reviewCount: 143,
    description: 'Layer bánh ladyfinger thấm espresso, kem mascarpone béo mịn, phủ cacao nguyên chất.',
    tags: ['signature'],
    calories: 380,
    prepMinutes: 1,
    inStock: true,
  },
  {
    id: 'menu_sandwich-ga',
    name: 'Sandwich Gà Nướng',
    categoryId: 'cat_do-an-nhe',
    price: 62000,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.6,
    reviewCount: 88,
    description: 'Ức gà nướng sốt mật ong, rau xà lách tươi, phô mai cheddar, bánh mì nướng bơ tỏi.',
    tags: ['new'],
    calories: 420,
    prepMinutes: 8,
    inStock: true,
  },
  {
    id: 'menu_salad-ca-hoi',
    name: 'Salad Cá Hồi Áp Chảo',
    categoryId: 'cat_do-an-nhe',
    price: 89000,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=800&auto=format&fit=crop',
    roast: null,
    rating: 4.7,
    reviewCount: 52,
    description: 'Cá hồi Na Uy áp chảo, rau mầm hữu cơ, sốt mè rang, hạt óc chó — lựa chọn lành mạnh.',
    tags: ['healthy'],
    calories: 340,
    prepMinutes: 10,
    inStock: false,
  },
];
